namespace QSB.EventsCore
{
    public enum EventType
    {
        Sector,
        ServerTime,
        AnimTrigger,
        FullState,
        FullStateRequest,
        FlashlightActiveChange,
        SignalscopeActiveChange,
        TranslatorActiveChange,
        ProbeLauncherActiveChange,
        SuitActiveChange,
        PlayerJoin,
        PlayerLeave,
        PlayerDeath,
        PlayerSectorChange,
        PlayerReady,
        ProbeActiveChange,
        Elevator,
        Geyser,
        OrbSlot,
        OrbUser,
        Conversation,
        ConversationStartEnd,
        PlayInstrument
    }
}
