namespace QSB.Events
{
	public enum EventType
	{
		Sector,
		ServerTime,
		AnimTrigger,
		PlayerState,
		PlayerStatesRequest,
		FlashlightActiveChange,
		SignalscopeActiveChange,
		TranslatorActiveChange,
		ProbeLauncherActiveChange,
		SuitActiveChange,
		PlayerJoin,
		PlayerDeath,
		PlayerSectorChange,
		PlayerReady,
		ProbeActiveChange,
		Elevator,
		Geyser,
		OrbSlot,
		OrbUser,
		Conversation,
		ConversationStartEnd,
		PlayInstrument,
		DialogueCondition,
		RevealFact
	}
}